name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
# branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download libraries
        run: sudo apt-get install libsdl2-dev libsdl2-mixer-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --release
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --release
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download libraries
        run: |
          brew install sdl2
          brew install sdl2_mixer
      - name: Add lib to path
        run: export LIBRARY_PATH="$LIBRARY_PATH:/opt/local/lib/"
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --release
